#!/bin/sh
cd /usr/tesla/UI/bin
LD_LIBRARY_PATH=/usr/tesla/UI/lib DISPLAY=:0 LD_PRELOAD=/itspowered.so ./QtCar -graphicssystem raster --cid --abs-speed -ic 192.168.90.101 --gw 192.168.90.102 --udp :20102 --udphp :31315 --ip 192.168.90.100 --touch evdev:/dev/input/event0,range:0,rangex:32768,rangey:32768
